services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Welcome.1997
      MYSQL_DATABASE: myDB
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  cypress:
    image: cypress/included:14.5.4
    depends_on:
      app:
        condition: service_started
    environment:
      - CYPRESS_baseUrl=http://app:3000
    volumes:
      - ./cypress/cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js
    working_dir: /e2e
    command: cypress run

volumes:
  mysql_data: